# Generated by Django 5.0.6 on 2024-06-20 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_accesskey_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 23, 4, 21, 455107, tzinfo=datetime.timezone.utc)),
        ),
    ]
